name: Build and Release

on:
  push:
    branches:
      - main # 触发条件，当代码合并到 main 分支时

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.0' # 使用 Go 1.21.0

      - name: Build for Windows x64
        run: GOOS=windows GOARCH=amd64 go build -o go_showstart_windows_amd64.exe

      - name: Build for Windows x32
        run: GOOS=windows GOARCH=386 go build -o go_showstart_windows_386.exe

      - name: Build for macOS Intel
        run: GOOS=darwin GOARCH=amd64 go build -o go_showstart_darwin_amd64

      - name: Build for macOS ARM
        run: GOOS=darwin GOARCH=arm64 go build -o go_showstart_darwin_arm64

      - name: Create release tag
        id: create_release
        run: echo "RELEASE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}

      - name: Upload Windows x64 asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go_showstart_windows_amd64.exe
          asset_name: go_showstart_windows_amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows x32 asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go_showstart_windows_386.exe
          asset_name: go_showstart_windows_386.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Intel asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go_showstart_darwin_amd64
          asset_name: go_showstart_darwin_amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go_showstart_darwin_arm64
          asset_name: go_showstart_darwin_arm64
          asset_content_type: application/octet-stream